### ISSUE TITLE
Support for regex and multiple status code

### ISSUE THREAD

**Issue by hax0rgb** [ethicalhackingplayground/erebus-templates#2]
It appears erebus does not support multiple status codes.

```
template:
   name: open-redirect
   severity: low
   author: gaurang
   description: Open Redirect

request:
   payloads: 
      - 'https://www.example.com'

   paths: false
response:
   statusCode: 
      - 301
      - 302
   patterns: 
      - 'Location: https://www.example.com'
```

The above template was validated using YAML Lint.

Running the above template, return the following error:

```
[ERR] yaml: unmarshal errors:
  line 14: cannot unmarshal !!seq into int
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x160862b]
```

Is there a template guide to create erebus templates? 

Also, I believe regex isn't supported yet. The best way to match Open redirect pattern is by using regex.

**Comment by hax0rgb** [comment]
Another thing I found is that erebus matches the pattern but Vulnerability is not flagged.

The following template was used:

```
template:
   name: open-redirect
   severity: low
   author: gaurang
   description: Open Redirect

request:
   payloads: 
      - 'https://www.example.com'

   paths: false
response:
   statusCode: 301
   patterns: 
      - 'Location: https://www.example.com'
```

Refer screenshot below which shows pattern is matched but the Vulnerability is not flagged.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/13043764/129522676-1f749609-f183-4e84-a605-08803f9282bf.png">
